import { PATHS } from './routes';

export enum Roles {
  ADMIN = 'ADMIN',
  CLIENT = 'CLIENT',
  HEALTHCARE_PROVIDER = 'HEALTHCARE_PROVIDER',
  HP_ADMIN = 'HP_ADMIN',
  HP_ADMINISTRATION = 'HP_ADMINISTRATION',
  HP_CL_MENTOR = 'HP_CL_MENTOR',
  HP_CLUSTER_LEADER = 'HP_CLUSTERLEIDER',
  HP_CONTRACT_MANAGER = 'HP_CONTRACT_MANAGER',
  HP_CUSTOMER_AGENCY = 'HP_CUSTOMER_AGENCY',
  HP_GUARDIAN = 'HP_GUARDIAN',
  MP_ADMIN = 'MP_ADMIN',
  MP_ADMINISTRATION = 'MP_ADMINISTRATION',
  MP_CONTRACT_MANAGER = 'MP_CONTRACT_MANAGER',
  MP_LEGAL_REPRESENTATIVE = 'MP_LEGAL_REPRESENTATIVE',
  MP_YOUTH_PROFESSIONAL = 'MP_YOUTH_PROFESSIONAL',
  MUNICIPALITY = 'MUNICIPALITY',
}

/** The first route in the access array is the default route **/
export const ACCESS = {
  [Roles.ADMIN]: [PATHS.DASHBOARD.ROOT],
  [Roles.CLIENT]: [PATHS.DASHBOARD.ROOT],
  [Roles.HEALTHCARE_PROVIDER]: [PATHS.DASHBOARD.ROOT],
  [Roles.HP_ADMIN]: [PATHS.DASHBOARD.ROOT],
  [Roles.HP_ADMINISTRATION]: [PATHS.DASHBOARD.ROOT],
  [Roles.HP_CL_MENTOR]: [PATHS.DASHBOARD.ROOT],
  [Roles.HP_CLUSTER_LEADER]: [PATHS.DASHBOARD.ROOT],
  [Roles.HP_CONTRACT_MANAGER]: [PATHS.DASHBOARD.ROOT],
  [Roles.HP_CUSTOMER_AGENCY]: [PATHS.DASHBOARD.ROOT],
  [Roles.HP_GUARDIAN]: [PATHS.DASHBOARD.ROOT],
  [Roles.MP_ADMIN]: [PATHS.DASHBOARD.ROOT],
  [Roles.MP_ADMINISTRATION]: [PATHS.DASHBOARD.ROOT],
  [Roles.MP_CONTRACT_MANAGER]: [PATHS.DASHBOARD.ROOT],
  [Roles.MP_LEGAL_REPRESENTATIVE]: [PATHS.DASHBOARD.ROOT],
  [Roles.MP_YOUTH_PROFESSIONAL]: [PATHS.DASHBOARD.ROOT],
  [Roles.MUNICIPALITY]: [PATHS.DASHBOARD.ROOT],
};
